class EventType:
    # ── User ──────────────────────────────────
    USER_REGISTERED      = 'USER_REGISTERED'
    USER_LOGIN_FAILED    = 'USER_LOGIN_FAILED'
    USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED'
    # ── Contract ──────────────────────────────
    CONTRACT_CREATED     = 'CONTRACT_CREATED'
    CONTRACT_UPDATED     = 'CONTRACT_UPDATED'
    VERSION_CREATED      = 'VERSION_CREATED'
    PARTY_INVITED        = 'PARTY_INVITED'
    PARTY_JOINED         = 'PARTY_JOINED'
    PARTY_APPROVED       = 'PARTY_APPROVED'
    APPROVAL_RESET       = 'APPROVAL_RESET'
    CONTRACT_LOCKED      = 'CONTRACT_LOCKED'
    CONTRACT_SIGNED      = 'CONTRACT_SIGNED'
    ALL_PARTIES_SIGNED   = 'ALL_PARTIES_SIGNED'
    CONTRACT_CANCELLED   = 'CONTRACT_CANCELLED'
    CONTRACT_COMPLETED   = 'CONTRACT_COMPLETED'
    PDF_EXPORTED         = 'PDF_EXPORTED'
    # ── Blockchain ────────────────────────────
    ON_CHAIN_SUBMITTED   = 'ON_CHAIN_SUBMITTED'
    ON_CHAIN_CONFIRMED   = 'ON_CHAIN_CONFIRMED'
    ON_CHAIN_FAILED      = 'ON_CHAIN_FAILED'
    # ── Invitations ───────────────────────────
    INVITATION_SENT      = 'INVITATION_SENT'
    INVITATION_ACCEPTED  = 'INVITATION_ACCEPTED'
    INVITATION_EXPIRED   = 'INVITATION_EXPIRED'