# Generated by Django 6.0.3 on 2026-05-12 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("design", "تصميم"),
                            ("software", "برمجة"),
                            ("content", "محتوى"),
                            ("retainer", "شهري"),
                            ("services", "خدمات عامة"),
                            ("marketing", "تسويق"),
                            ("consulting", "استشارات"),
                            ("legal", "قانوني"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255)),
                ("body_ar", models.TextField()),
                ("body_en", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_templates",
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("deleted_at__isnull", True), ("is_active", True)
                        ),
                        fields=["category"],
                        name="templates_active_idx",
                    )
                ],
            },
        ),
    ]
