# Generated by Django 6.0.3 on 2026-05-12 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates_lib", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_ar", models.CharField(max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255)),
                ("description_ar", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("PENDING_SIGNATURES", "بانتظار التوقيعات"),
                            ("SIGNED", "موقّع"),
                            ("COMPLETED", "مكتمل"),
                            ("CANCELLED", "ملغي"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "canonical_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="templates_lib.contracttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("canonical_json", models.JSONField(default=dict)),
                ("change_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="contracts.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_versions",
                "ordering": ["version_number"],
                "unique_together": {("contract", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_index", models.PositiveIntegerField()),
                (
                    "clause_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "عام"),
                            ("PAYMENT", "دفع"),
                            ("DELIVERY", "تسليم"),
                            ("PENALTY", "غرامة"),
                            ("CUSTOM", "مخصص"),
                        ],
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                ("title_ar", models.CharField(blank=True, max_length=300)),
                ("title_en", models.CharField(blank=True, max_length=300)),
                ("content_ar", models.TextField()),
                ("content_en", models.TextField(blank=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="contracts.contractversion",
                    ),
                ),
            ],
            options={
                "db_table": "contract_clauses",
                "ordering": ["order_index"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_contract",
                to="contracts.contractversion",
            ),
        ),
        migrations.CreateModel(
            name="ContractParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("CREATOR", "منشئ"), ("PARTY", "طرف")], max_length=20
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("PENDING", "معلّق"), ("APPROVED", "موافق")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="contracts.contract",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="contract_parties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_parties",
                "indexes": [models.Index(fields=["user"], name="parties_user_idx")],
                "unique_together": {("contract", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["status"], name="contracts_status_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["-created_at"], name="contracts_created_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["canonical_hash"], name="contracts_hash_idx"),
        ),
    ]
