# Generated by Django 6.0.3 on 2026-05-12 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChainTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("CONTRACT_REGISTER", "تسجيل عقد")], max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "معلّق"),
                            ("SUBMITTED", "مُرسَل"),
                            ("CONFIRMED", "مؤكّد"),
                            ("FAILED", "فشل"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                ("contract_hash", models.CharField(max_length=64)),
                ("tx_hash", models.CharField(blank=True, max_length=66)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="chain_transactions",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "chain_transactions",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="chain_pending_idx"
                    ),
                    models.Index(
                        fields=["contract", "-created_at"], name="chain_contract_idx"
                    ),
                ],
            },
        ),
    ]
