# Generated by Django 6.0.3 on 2026-05-12 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_REGISTERED", "مستخدم سجّل"),
                            ("USER_LOGIN_FAILED", "فشل تسجيل دخول"),
                            ("USER_PROFILE_UPDATED", "ملف شخصي حُدِّث"),
                            ("CONTRACT_CREATED", "عقد أُنشئ"),
                            ("CONTRACT_UPDATED", "عقد حُدِّث"),
                            ("VERSION_CREATED", "نسخة جديدة"),
                            ("PARTY_INVITED", "طرف دُعي"),
                            ("PARTY_JOINED", "طرف انضم"),
                            ("PARTY_APPROVED", "طرف وافق"),
                            ("APPROVAL_RESET", "موافقات أُعيدت"),
                            ("CONTRACT_LOCKED", "عقد قُفل للتوقيع"),
                            ("CONTRACT_SIGNED", "طرف وقّع"),
                            ("ALL_PARTIES_SIGNED", "جميع الأطراف وقّعوا"),
                            ("CONTRACT_CANCELLED", "عقد أُلغي"),
                            ("CONTRACT_COMPLETED", "عقد اكتمل"),
                            ("PDF_EXPORTED", "PDF صُدِّر"),
                            ("ON_CHAIN_TX_SUBMITTED", "معاملة أُرسلت"),
                            ("ON_CHAIN_TX_CONFIRMED", "معاملة أُكِّدت"),
                            ("ON_CHAIN_TX_FAILED", "معاملة فشلت"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="audit_events",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "db_table": "audit_events",
                "indexes": [
                    models.Index(
                        fields=["contract", "-created_at"], name="audit_contract_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="audit_actor_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"], name="audit_type_idx"
                    ),
                ],
            },
        ),
    ]
