# Generated by Django 6.0.5 on 2026-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('USER_REGISTERED', 'مستخدم سجّل'), ('USER_LOGIN_FAILED', 'فشل تسجيل دخول'), ('USER_PROFILE_UPDATED', 'ملف شخصي حُدِّث'), ('SUBSCRIPTION_ACTIVATED', 'اشتراك فُعِّل'), ('CONTRACT_CREATED', 'عقد أُنشئ'), ('CONTRACT_UPDATED', 'عقد حُدِّث'), ('VERSION_CREATED', 'نسخة جديدة'), ('PARTY_INVITED', 'طرف دُعي'), ('PARTY_JOINED', 'طرف انضم'), ('PARTY_APPROVED', 'طرف وافق'), ('APPROVAL_RESET', 'موافقات أُعيدت'), ('CONTRACT_LOCKED', 'عقد قُفل للتوقيع'), ('CONTRACT_SIGNED', 'طرف وقّع'), ('ALL_PARTIES_SIGNED', 'جميع الأطراف وقّعوا'), ('CONTRACT_CANCELLED', 'عقد أُلغي'), ('CONTRACT_COMPLETED', 'عقد اكتمل'), ('PDF_EXPORTED', 'PDF صُدِّر'), ('ON_CHAIN_TX_SUBMITTED', 'معاملة أُرسلت'), ('ON_CHAIN_TX_CONFIRMED', 'معاملة أُكِّدت'), ('ON_CHAIN_TX_FAILED', 'معاملة فشلت')], max_length=50),
        ),
    ]
