# Generated by Django 6.0.3 on 2026-05-12 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signed_hash", models.CharField(max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="signatures",
                        to="contracts.contract",
                    ),
                ),
                (
                    "contract_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="signatures",
                        to="contracts.contractversion",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "signatures",
                "indexes": [
                    models.Index(
                        fields=["contract", "signed_at"], name="signatures_contract_idx"
                    ),
                    models.Index(fields=["signer"], name="signatures_signer_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "signer"),
                        name="signatures_unique_per_party",
                    )
                ],
            },
        ),
    ]
