"""
Django settings for Mithaq project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url
from decouple import config


BASE_DIR = Path(__file__).resolve().parent.parent



TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="")
TWILIO_PHONE_NUMBER = config("TWILIO_PHONE_NUMBER", default="")


RESEND_API_KEY = config("RESEND_API_KEY")

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

SITE_URL = config("SITE_URL", default="http://127.0.0.1:8000")


SECRET_KEY = config('SECRET_KEY')


DEBUG = config('DEBUG', cast=bool, default=False)


_allowed_hosts_env = config('ALLOWED_HOSTS', default='localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]


_csrf_origins_env = config('CSRF_TRUSTED_ORIGINS', default='https://kept-justify-wincing.ngrok-free.dev')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins_env.split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',

    'rest_framework',
    'rest_framework_simplejwt',

    'core',
    'accounts',
    'audit',
    'blockchain',
    'invitations',
    'contracts',
    'dashboard',
    'milestones',
    'notifications',
    'payments',
    'signatures',
    'subscriptions',
    'wallet',
    'templates_lib',
    'verification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Mithaq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates' / 'core'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mithaq.wsgi.application'








DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600, conn_health_checks=True)
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour', 
    },
}


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


AUTH_USER_MODEL = 'accounts.User'

MOYASAR_API_KEY         = config('MOYASAR_SECRET_KEY')
MOYASAR_PUBLISHABLE_KEY = config('MOYASAR_PUBLISHABLE_KEY')

MOYASAR_BASE_URL        = 'https://api.moyasar.com/v1'
MOYASAR_CALLBACK_URL    = config('MOYASAR_CALLBACK_URL', default='http://localhost:8000/api/payments/callback/')

LOGIN_URL = "accounts:sign_in"
LOGIN_REDIRECT_URL = "accounts:profile"


(BASE_DIR / 'logs').mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_file': {
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'logs' / 'mail.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
    
        'django.request': {
            'handlers': ['console', 'mail_file'],
            'level': 'ERROR',
            'propagate': False,
        },
   
        'django.core.mail': {
            'handlers': ['console', 'mail_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
  
        'invitations': {
            'handlers': ['console', 'mail_file'],
            'level': 'DEBUG',
            'propagate': False,
        },

        'accounts': {
            'handlers': ['console', 'mail_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

EMAIL_TIMEOUT = 20